Change exception system
Rainist/K-Format pull request #16
Opened 2019-07-20 08:55 UTC by JungWinter

> 이 PR은 breaking change를 포함하고 있습니다.

## 변경점

* 별도의 exception class를 만들었습니다.
* `kproperty`에서 길이가 맞지 않을 때 `ValueError` 대신 `KFormatError`를 상속받은 `TooLongValueError`를 raise합니다.
* `kclass`에서 발생하는 에러 메시지를 명시적으로 바꿔주었습니다.
	* 라이브러리 사용자에게 좋은 에러 메시지는 _왜 에러가 발생했는지_ 이상으로 _어떻게 해야 에러를 해결할 수 있는지_ 알려주는 메시지라고 생각했습니다.
	* 변경된 메시지 포맷은 https://github.com/Rainist/K-Format/commit/db00250c61afbb9d7ba67055222d6b85784a8285 커밋에서 확인 가능합니다.
	* `AN cannot accept ... type` 메시지가 좀 장황해진 느낌인데 코멘트 부탁드립니다.
* `kclass`의 property로 `KProperty`가 선언되지 않았을 때 발생하던 에러를 조기에 발생시킵니다.
	* as-is: 클래스 선언 후 인스턴스 생성 시점
	* to-be: 클래스 선언 시점
* [Rainist/styleguide](https://github.com/Rainist/styleguide/blob/master/python/README.md) 컨벤션에 맞게 수정했고 [Rainist/python](https://github.com/Rainist/python) 설정에 맞는 `black` & `isort` 스타일을 적용시켰습니다.
	* 별도의 `Makefile`을 본 PR에 포함시키진 않았습니다.
* 변경점과 관련된 에러케이스 테스트를 추가했습니다.

Resolve #11

2019-07-20 11:10 UTC, 0xd669 requested changes
👍👍

2019-07-20 11:10 UTC, 0xd669 commented on kformat/exception.py
> +class WrongTypeError(KFormatError):
지금 네이밍도 좋지만 `UnexpectedTypeError`는 어떠신가요? '틀린' 타입보다는 '예상한 것과 다른' 타입이 좀 더 의미에 맞는 것 같아서요 🤔

2019-07-20 11:10 UTC, 0xd669 commented on kformat/exception.py
> +    def __init__(self, expect: Type, value):
```suggestion
    def __init__(self, expected: Type, value):
```

2019-07-20 11:10 UTC, 0xd669 commented on kformat/exception.py
> +        self.expect = expect
```suggestion
        self.expected = expected
```

2019-07-20 11:10 UTC, 0xd669 commented on kformat/exception.py
> +        return f'Should be "{_name(self.expect)}" instead of "{_name(self.value)}"'
```suggestion
        return f'"{_name(self.expected)}" is expected, but "{_name(self.value)}" is given'
```

2019-07-20 11:10 UTC, sunghyunzz commented on kformat/exception.py
> +class TooLongValueError(KFormatError):
현재 유즈케이스에서는 "too long"이 맞지만 앞으로 등장할 수 있는 길이와 관련된 상황을 고려해 다음과 같은 에러명은 어떠신가요?

- `LengthError`
- `InvalidLengthError`
- `InvalidLengthValueError`
- `LengthValueError`

2019-07-20 11:10 UTC, sunghyunzz commented on kformat/exception.py
> +        return f'Too long value is given(max: {self.length})'
```suggestion
        return f'Invalid length of value is given(expected: {self.length})'
```

그리고 만약 위 오류명 변경 제안에 동의하신다면 위와 같이 메시지를 바꾸면 어떨까 합니다.

2019-07-20 11:10 UTC, sunghyunzz commented on kformat/kclass.py
> +            not _is_prop_kclass(prop)
```python
def _is_valid_child_prop(prop) -> bool:
    return _is_prop_kclass(prop) or _is_prop_list(prop) or isinstance(prop, kproperty.KProperty)
```

위와 같은 함수를 추가하고

```python
if not _is_valid_child_prop(prop):
    raise WrongTypeError(...)
```
 
이렇게 구성하는 편이 가독성 면에서 좋을 것 같아요.

2019-07-20 11:10 UTC, sunghyunzz commented on kformat/kclass.py
> +                    if not getattr(item, KCLASS_ANNOTATION, False):
```suggestion
                    if not _is_prop_kclass(item):
```

2019-07-20 11:10 UTC, sunghyunzz commented on kformat/kclass.py
> +                    expects = ', '.join(
`expected_types` 가 좀 더 명확한 이름일 것 같습니다.

2019-07-20 11:55 UTC, JungWinter commented on kformat/exception.py
> +class WrongTypeError(KFormatError):
👌 코드 곳곳에 `expected_types`로 체크하는 부분이 있으니 그게 더 자연스러울거같네요

2019-07-20 11:57 UTC, JungWinter commented on kformat/exception.py
> +class TooLongValueError(KFormatError):
✅ `InvalidLengthError`가 제일 자연스러워 보이네용

2019-07-24 05:23 UTC, 0xd669 approved these changes
L.G.T.M 👍

2019-07-24 05:23 UTC, merged