Support keyword arguments in init
Rainist/K-Format pull request #21
Opened 2019-07-20 13:46 UTC by JungWinter

Resolve #13 

## 정해야 하는 부분

아래와 같은 상황에서 error를 발생시킬 것인지 허용할 것인지 정책을 정해야합니다.

```py
one = Other(123, an='1', n=456)
assert (one.n[1], one.an[1]) == (456, '1')  # OK in K-Format?
```

보통의 경우 아래처럼 에러가 발생합니다.

```py
def func(a, b):
    return a, b

func(1, b=2, a=3)
# TypeError: func() got multiple values for argument 'a'
```

2019-07-24 05:27 UTC, 0xd669 reviewed
이 라이브러리를 이용해 생성한 dataclass가 일반적인 dataclass와 동일하게 사용될 수 있는 게 궁극적인 목표이기 때문에 언급해주신 상황에서는 오류가 발생하는 게 맞을 것 같습니다. 

따라서 `TypeError: __init__() got multiple values for argument 'n'` 오류가 발생해야할 것 같아요.

2019-07-26 02:50 UTC, JungWinter commented
`dataclass`의 구현을 참고해 런타임에 `__init__`함수를 생성하도록 변경하였고 기존 `init` 함수의 validate 로직은 `__post_init__`으로 분리시켰습니다.

2019-07-26 09:29 UTC, 0xd669 requested changes
정말 매직매직하네요~ 🔮

2019-07-26 09:29 UTC, sunghyunzz commented on kformat/kclass.py
> +    setattr(cls, '__post_init__', post_init)
`__post_init__` 은 모듈 레벨 상수로 정의되어 통일된 형태로 사용해야할 것 같습니다 🔮

2019-07-26 09:29 UTC, sunghyunzz commented on kformat/kclass.py
> +    return ['self'] + [k for k, _ in props]
```suggestion
    return ['self', *(k for k, _ in props)]
```

2019-07-26 09:29 UTC, sunghyunzz commented on kformat/kclass.py
> +    locals = {}
충돌을 피하기 위해 `locals_`는 어떨까요?

2019-07-26 09:29 UTC, sunghyunzz commented on kformat/kclass.py
> +    exec(txt, {}, locals)
`locals_` 선언을 이 문장 바로 위에 하고, 위 로직들과 공백 하나 두면 좋을 것 같아요~

2019-07-26 09:40 UTC, 0xd669 approved these changes
L.G.T.M

2019-07-26 09:40 UTC, merged