Makefile 추가
Rainist/K-Format pull request #25
Opened 2019-08-24 12:35 UTC by JungWinter

Resolve #24

2019-08-24 13:00 UTC, xissy commented
Looks good to me.

2019-08-27 03:29 UTC, 0xd669 requested changes
`.PHONY` 이런 스타일로 작성하는 게 훨씬 좋아보이네요 :+1:

2019-08-27 03:29 UTC, sunghyunzz commented on Makefile
> +.PHONY: lint
```suggestion
.PHONY: coverage
```

2019-08-27 03:29 UTC, sunghyunzz commented on Makefile
> +# vi: ft=make
```suggestion
```
특정 에디터에 대한 설정은 에디터 사용자가 직접 설정해 사용하는 편이 좋을 것 같습니다.

2019-08-27 04:34 UTC, 0xd669 approved these changes
👍👍

2019-08-27 04:35 UTC, merged